name: 'build docker image'
description: 'build docker image'
inputs:
  docker_hub_user:  # id of input
    description: 'docker hub user'
    required: true
  docker_hub_token: # id of input
    description: 'docker hub token'
    required: true
  image_name: # id of input
    description: 'image name'
    required: true

runs:
  using: "composite"
  steps:
    - name: docker login
      run: |
        echo ${{ inputs.docker_hub_token }} > password.txt
        cat password.txt | docker login --username ${{ inputs.docker_hub_user }} --password-stdin
        echo $pwd
        echo $DOCKER_HUB_TOKEN
        password.txt
      shell: bash
    - name: build image
      run: |
        docker image build -t ${{ inputs.docker_hub_user }}/${{ inputs.image_Name }}
      shell: bash
    - name : push image
      run: |
        docker image push ${{ inputs.docker_hub_user }}/${{ inputs.image_Name }}
      shell: bash
