{{- $webDomain := printf "%s.%s" "otmoiclp" .Values.user.zone -}}
# Source: obridge-lpnode/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lpnode-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: otmoiclp
  type: ClusterIP
  ports:
    - protocol: TCP
      name: lpnode-api
      port: 9202
      targetPort: 9202
---
# Source: obridge-lpnode/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otmoiclp
  namespace: {{ .Release.Namespace }}
  labels:
    app: otmoiclp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otmoiclp
  template:
    metadata:
      labels:
        app: otmoiclp
    spec:
      containers:
      - name: otmoiclp
        image: kldtks/edge:otmoic-lpnode-latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9202
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: obridge-lpnode-db-redis
                key: redis-password
          - name: LPNODE_URI
            value: "https://{{ $webDomain }}/lpnode"
          - name: RELAY_URI
            value: "https://otmoicrelay.saidev.snowinning.com/relay"
