name: build-docker-image
on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  build-docker-image:
  runs-on: ubuntu-22.04
  rnv:
  steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: build docker image
      uses: ./.github/actions/docker
      with:
        docker_hub_user : ${{ secrets.DOCKER_HUB_USER }}
        docker_hub_token : ${{ secrets.DOCKER_HUB_TOKEN }}
        image_name: test:latest